//@ sourceMappingURL=main2.map
// Generated by CoffeeScript 1.6.1

(function(win, doc, exports) {
  var Camera, Cube, DEG_TO_RAD, Face, MOUSE_DOWN, MOUSE_MOVE, MOUSE_UP, Matrix4, PI, Particle, Renderer, Scene, Texture, Triangle, Vector3, camera, cos, dragging, ground_1_uv, ground_2_uv, init, isTouch, prevX, prevY, renderer, roof_1_uv, roof_2_uv, rotX, rotY, scene, sin, tan, textureImage, wall_1_uv, wall_2_uv, wall_3_uv, wall_4_uv, wall_5_uv, wall_6_uv, wall_7_uv, wall_8_uv, _ref;
  tan = Math.tan, cos = Math.cos, sin = Math.sin, PI = Math.PI;
  _ref = window.S3D, Face = _ref.Face, Cube = _ref.Cube, Texture = _ref.Texture, Triangle = _ref.Triangle, Matrix4 = _ref.Matrix4, Camera = _ref.Camera, Renderer = _ref.Renderer, Scene = _ref.Scene, Vector3 = _ref.Vector3, Particle = _ref.Particle;
  DEG_TO_RAD = PI / 180;
  isTouch = 'ontouchstart' in window;
  MOUSE_DOWN = isTouch ? 'touchstart' : 'mousedown';
  MOUSE_MOVE = isTouch ? 'touchmove' : 'mousemove';
  MOUSE_UP = isTouch ? 'touchend' : 'mouseup';
  ground_1_uv = [0, 0, 0.5, 0, 0, 0.5];
  ground_2_uv = [0, 0.5, 0.5, 0, 0.5, 0.5];
  roof_1_uv = [0, 0, 0.5, 0, 0, 0.5];
  roof_2_uv = [0, 0.5, 0.5, 0, 0.5, 0.5];
  wall_1_uv = [0, 0.5, 0.5, 0.5, 0, 1];
  wall_2_uv = [0, 1, 0.5, 0.5, 0.5, 1];
  wall_3_uv = [0.5, 0, 1, 0, 0.5, 0.5];
  wall_4_uv = [0.5, 0.5, 1, 0, 1, 0.5];
  wall_5_uv = [0.5, 0, 1, 0, 0.5, 0.5];
  wall_6_uv = [0.5, 0.5, 1, 0, 1, 0.5];
  wall_7_uv = [0, 0.5, 0.5, 0.5, 0, 1];
  wall_8_uv = [0, 1, 0.5, 0.5, 0.5, 1];
  textureImage = null;
  rotX = 0;
  rotY = 0;
  renderer = null;
  camera = null;
  scene = null;
  init = function() {
    var aspect, create, ctx, cv, fov, h, img, w;
    cv = doc.getElementById('canvas');
    ctx = cv.getContext('2d');
    w = cv.width = win.innerWidth;
    h = cv.height = win.innerHeight;
    fov = 60;
    aspect = w / h;
    img = new Image();
    img.onload = function() {
      textureImage = img;
      return create();
    };
    img.src = 'img/aXjiA.png';
    camera = new Camera(60, aspect, 5, 2000);
    camera.position.x = 10;
    camera.position.y = 50;
    camera.position.z = 80;
    camera.lookAt(new Vector3(0, 0, 0));
    scene = new Scene;
    renderer = new Renderer(cv, '#eee');
    return create = function() {
      var cube1, cube2, cube3, materials;
      materials = [new Texture(textureImage, roof_1_uv), new Texture(textureImage, roof_2_uv), new Texture(textureImage, wall_1_uv), new Texture(textureImage, wall_2_uv), new Texture(textureImage, wall_3_uv), new Texture(textureImage, wall_4_uv), new Texture(textureImage, wall_5_uv), new Texture(textureImage, wall_6_uv), new Texture(textureImage, wall_3_uv), new Texture(textureImage, wall_4_uv), new Texture(textureImage, wall_5_uv), new Texture(textureImage, wall_6_uv), new Texture(textureImage, wall_7_uv), new Texture(textureImage, wall_8_uv)];
      cube1 = new Cube(20, 20, 20, 1, 1, 1, materials);
      cube1.position.z = -50;
      cube1.rotation.z = 30;
      cube2 = new Cube(20, 20, 20, 1, 1, 1, materials);
      cube2.position.z = -150;
      cube2.position.x = 50;
      cube3 = new Cube(20, 20, 20, 1, 1, 1, materials);
      cube3.position.z = -350;
      cube3.position.x = 50;
      cube3.position.y = 80;
      scene.add(cube3);
      scene.add(cube2);
      scene.add(cube1);
      return renderer.render(scene, camera);
    };
  };
  dragging = false;
  prevX = 0;
  prevY = 0;
  win.addEventListener('mousewheel', function(e) {
    camera.position.z += e.wheelDelta / 100;
    renderer.render(scene, camera);
    return e.preventDefault();
  }, false);
  doc.addEventListener('touchstart', function(e) {
    return e.preventDefault();
  }, false);
  doc.addEventListener(MOUSE_DOWN, function(e) {
    dragging = true;
    prevX = isTouch ? e.touches[0].pageX : e.pageX;
    return prevY = isTouch ? e.touches[0].pageY : e.pageY;
  }, false);
  doc.addEventListener(MOUSE_MOVE, function(e) {
    var pageX, pageY;
    if (dragging === false) {
      return;
    }
    pageX = isTouch ? e.touches[0].pageX : e.pageX;
    pageY = isTouch ? e.touches[0].pageY : e.pageY;
    rotY += (prevX - pageX) / 100;
    rotX += (prevY - pageY) / 100;
    camera.setWorld(Matrix4.multiply((new Matrix4()).rotationY(rotY), (new Matrix4()).rotationX(rotX)));
    prevX = pageX;
    prevY = pageY;
    return renderer.render(scene, camera);
  }, false);
  doc.addEventListener(MOUSE_UP, function(e) {
    return dragging = false;
  }, false);
  return doc.addEventListener('DOMContentLoaded', init, false);
})(window, window.document, window);
