//@ sourceMappingURL=sky.map
// Generated by CoffeeScript 1.6.1

(function(win, doc, exports) {
  var $, AmbientLight, Camera, Color, Cube, DEG_TO_RAD, DirectionalLight, Face, Face2, Line, MOUSE_DOWN, MOUSE_MOVE, MOUSE_UP, Matrix4, Object3D, PI, Particle, Plate, Renderer, Scene, Texture, Triangle, Vector3, camera, cos, init, isTouch, renderer, requestAnimFrame, scene, sin, tan, _ref;
  tan = Math.tan, cos = Math.cos, sin = Math.sin, PI = Math.PI;
  _ref = window.S3D, Face2 = _ref.Face2, Object3D = _ref.Object3D, Line = _ref.Line, Color = _ref.Color, AmbientLight = _ref.AmbientLight, DirectionalLight = _ref.DirectionalLight, Plate = _ref.Plate, Face = _ref.Face, Cube = _ref.Cube, Texture = _ref.Texture, Triangle = _ref.Triangle, Matrix4 = _ref.Matrix4, Camera = _ref.Camera, Renderer = _ref.Renderer, Scene = _ref.Scene, Vector3 = _ref.Vector3, Particle = _ref.Particle;
  $ = function(selector) {
    return doc.querySelector(selector);
  };
  requestAnimFrame = (function() {
    return win.requestAnimationFrame || win.webkitRequestAnimationFrame || win.mozRequestAnimationFrame || win.msRequestAnimationFrame || function(callback) {
      return setTimeout(callback, 16);
    };
  })();
  DEG_TO_RAD = PI / 180;
  isTouch = 'ontouchstart' in window;
  MOUSE_DOWN = isTouch ? 'touchstart' : 'mousedown';
  MOUSE_MOVE = isTouch ? 'touchmove' : 'mousemove';
  MOUSE_UP = isTouch ? 'touchend' : 'mouseup';
  renderer = null;
  camera = null;
  scene = null;
  init = function() {
    var aspect, base, create, ctx, cv, dragging, fov, h, hSize, moveX, moveY, prevX, prevY, size, startZoom, w;
    cv = doc.getElementById('canvas');
    ctx = cv.getContext('2d');
    w = cv.width = win.innerWidth;
    h = cv.height = win.innerHeight;
    fov = 60;
    aspect = w / h;
    size = 1024;
    hSize = size * 0.5;
    camera = new Camera(60, aspect, 1, 10000);
    camera.position.set(0, 0, 10);
    camera.lookAt(new Vector3(0, 0, 0));
    camera.lookAtLock = true;
    scene = new Scene;
    renderer = new Renderer(cv, '#111');
    renderer.fog = false;
    create = function() {
      var ambLight, backImg, bottomImg, container, div, face1, face2, face3, face4, face5, face6, frontImg, i, leftImg, line, rightImg, topImg, x, z, _i, _j, _ref1, _ref2;
      frontImg = $('#texture > .front');
      backImg = $('#texture > .back');
      leftImg = $('#texture > .left');
      rightImg = $('#texture > .right');
      topImg = $('#texture > .top');
      bottomImg = $('#texture > .bottom');
      div = 3;
      face1 = new Face2(size, size, div, div, frontImg, frontImg);
      face1.position.z = -hSize;
      scene.add(face1);
      face2 = new Face2(size, size, div, div, rightImg, rightImg);
      face2.rotation.y = -90;
      face2.position.x = hSize;
      scene.add(face2);
      face3 = new Face2(size, size, div, div, leftImg, leftImg);
      face3.rotation.y = 90;
      face3.position.x = -hSize;
      scene.add(face3);
      face4 = new Face2(size, size, div, div, backImg, backImg);
      face4.rotation.y = 180;
      face4.position.z = hSize;
      scene.add(face4);
      face5 = new Face2(size, size, div, div, bottomImg, bottomImg);
      face5.rotation.x = -90;
      face5.position.y = -hSize;
      scene.add(face5);
      face6 = new Face2(size, size, div, div, topImg, topImg);
      face6.rotation.x = 90;
      face6.position.y = hSize;
      scene.add(face6);
      container = new Object3D;
      container.position.x = -(size * 0.5);
      container.position.z = -(size * 0.5);
      for (i = _i = 0, _ref1 = size / 10; 0 <= _ref1 ? _i <= _ref1 : _i >= _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
        z = i * 10;
        line = new Line(0, 0, z, size, 0, z, new Color(255, 255, 255, 0.3));
        container.add(line);
      }
      for (i = _j = 0, _ref2 = size / 10; 0 <= _ref2 ? _j <= _ref2 : _j >= _ref2; i = 0 <= _ref2 ? ++_j : --_j) {
        x = i * 10;
        line = new Line(x, 0, 0, x, 0, size, new Color(255, 255, 255, 0.3));
        container.add(line);
      }
      ambLight = new AmbientLight(1.0);
      scene.add(ambLight);
      return renderer.render(scene, camera);
    };
    create();
    dragging = false;
    prevX = 0;
    prevY = 0;
    win.addEventListener('mousewheel', function(e) {
      camera.position.z += e.wheelDelta / 100;
      renderer.render(scene, camera);
      return e.preventDefault();
    }, false);
    base = 100;
    startZoom = 0;
    document.addEventListener('gesturechange', function(e) {
      var num;
      num = e.scale * base - base;
      camera.position.z = startZoom - num;
      renderer.render(scene, camera);
      return e.preventDefault();
    }, false);
    document.addEventListener('gesturestart', function() {
      return startZoom = camera.position.z;
    }, false);
    doc.addEventListener('touchstart', function(e) {
      return e.preventDefault();
    }, false);
    doc.addEventListener(MOUSE_DOWN, function(e) {
      dragging = true;
      prevX = isTouch ? e.touches[0].pageX : e.pageX;
      return prevY = isTouch ? e.touches[0].pageY : e.pageY;
    }, false);
    moveX = camera.position.x;
    moveY = camera.position.y;
    doc.addEventListener(MOUSE_MOVE, function(e) {
      var limit, pageX, pageY;
      if (dragging === false) {
        return;
      }
      pageX = isTouch ? e.touches[0].pageX : e.pageX;
      pageY = isTouch ? e.touches[0].pageY : e.pageY;
      moveX -= (prevX - pageX) % 360;
      moveY += prevY - pageY;
      limit = 300;
      if (moveY > limit) {
        moveY = limit;
      }
      if (moveY < -limit) {
        moveY = -limit;
      }
      camera.position.y = moveY;
      camera.position.x = sin(moveX * DEG_TO_RAD) * 500 * 0.5;
      camera.position.z = cos(moveX * DEG_TO_RAD) * 500 * 0.5;
      prevX = pageX;
      prevY = pageY;
      return renderer.render(scene, camera);
    }, false);
    return doc.addEventListener(MOUSE_UP, function(e) {
      return dragging = false;
    }, false);
  };
  return doc.addEventListener('DOMContentLoaded', init, false);
})(window, window.document, window);
