//@ sourceMappingURL=sphere-card.map
// Generated by CoffeeScript 1.6.1

(function(win, doc, exports) {
  var $, AmbientLight, Camera, Color, Cube, DEG_TO_RAD, DirectionalLight, Face, Face2, Line, MOUSE_DOWN, MOUSE_MOVE, MOUSE_UP, Matrix4, Object3D, PI, Particle, Plate, RAD_TO_DEG, Renderer, Scene, Texture, Triangle, Vector3, atan2, camera, cos, init, isTouch, random, renderer, requestAnimFrame, rotX, rotY, scene, sin, tan, _ref;
  atan2 = Math.atan2, random = Math.random, tan = Math.tan, cos = Math.cos, sin = Math.sin, PI = Math.PI;
  _ref = window.S3D, Face2 = _ref.Face2, Object3D = _ref.Object3D, Line = _ref.Line, Color = _ref.Color, AmbientLight = _ref.AmbientLight, DirectionalLight = _ref.DirectionalLight, Plate = _ref.Plate, Face = _ref.Face, Cube = _ref.Cube, Texture = _ref.Texture, Triangle = _ref.Triangle, Matrix4 = _ref.Matrix4, Camera = _ref.Camera, Renderer = _ref.Renderer, Scene = _ref.Scene, Vector3 = _ref.Vector3, Particle = _ref.Particle;
  $ = function(selector) {
    return doc.querySelector(selector);
  };
  requestAnimFrame = (function() {
    return win.requestAnimationFrame || win.webkitRequestAnimationFrame || win.mozRequestAnimationFrame || win.msRequestAnimationFrame || function(callback) {
      return setTimeout(callback, 16);
    };
  })();
  DEG_TO_RAD = PI / 180;
  RAD_TO_DEG = 180 / PI;
  isTouch = 'ontouchstart' in window;
  MOUSE_DOWN = isTouch ? 'touchstart' : 'mousedown';
  MOUSE_MOVE = isTouch ? 'touchmove' : 'mousemove';
  MOUSE_UP = isTouch ? 'touchend' : 'mouseup';
  rotX = 0;
  rotY = 0;
  renderer = null;
  camera = null;
  scene = null;
  init = function() {
    var aspect, base, create, ctx, cv, dragging, fov, h, moveX, moveY, prevX, prevY, startZoom, w;
    cv = doc.getElementById('canvas');
    ctx = cv.getContext('2d');
    w = cv.width = win.innerWidth;
    h = cv.height = win.innerHeight;
    fov = 60;
    aspect = w / h;
    camera = new Camera(40, aspect, 0.1, 10000);
    camera.position.x = 0;
    camera.position.y = 120;
    camera.position.z = 320;
    camera.lookAt(new Vector3(0, 50, 0));
    camera.lookAtLock = true;
    scene = new Scene;
    renderer = new Renderer(cv, '#111');
    renderer.fogEnd = 10000;
    create = function() {
      var ambLight, angle, container, dirLight, i, line, line1, line2, line3, plate, r, s, size, start, step, t, x, y, z, _i, _j, _k, _l, _loop, _ref1, _ref2, _s, _t;
      size = 200;
      line1 = new Line(0, 0, -size / 2, 0, 0, size / 2, new Color(255, 0, 0, 0.3));
      line2 = new Line(-size / 2, 0, 0, size / 2, 0, 0, new Color(0, 255, 0, 0.3));
      line3 = new Line(0, size / 2, 0, 0, -size / 2, 0, new Color(0, 0, 255, 0.3));
      container = new Object3D;
      container.position.x = -(size * 0.5);
      container.position.z = -(size * 0.5);
      for (i = _i = 0, _ref1 = size / 10; 0 <= _ref1 ? _i <= _ref1 : _i >= _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
        z = i * 10;
        line = new Line(0, 0, z, size, 0, z, new Color(255, 255, 255, 0.3));
        container.add(line);
      }
      for (i = _j = 0, _ref2 = size / 10; 0 <= _ref2 ? _j <= _ref2 : _j >= _ref2; i = 0 <= _ref2 ? ++_j : --_j) {
        x = i * 10;
        line = new Line(x, 0, 0, x, 0, size, new Color(255, 255, 255, 0.3));
        container.add(line);
      }
      ambLight = new AmbientLight(0.1);
      dirLight = new DirectionalLight(0.8, (new Vector3(1, 0, 1)).normalize());
      scene.add(ambLight);
      scene.add(dirLight);
      r = 100;
      step = 60;
      start = 0;
      for (s = _k = start; step > 0 ? _k < 360 : _k > 360; s = _k += step) {
        for (t = _l = start; step > 0 ? _l < 360 : _l > 360; t = _l += step) {
          _s = s * DEG_TO_RAD;
          _t = t * DEG_TO_RAD;
          x = r * cos(_s) * sin(_t);
          z = r * sin(_s) * sin(_t);
          y = r * cos(_t);
          plate = new Plate(20, 20, 1, 1, new Color(255, 0, 0, 1), new Color(255, 0, 0, 1), new Color(0, 0, 255, 1), new Color(0, 0, 255, 1));
          plate.position.set(x, y, z);
          plate.rotation.y = y;
          plate.rotation.x = x;
          scene.add(plate);
        }
      }
      scene.add(container);
      scene.add(line1);
      scene.add(line2);
      scene.add(line3);
      angle = 0;
      return (_loop = function() {
        angle = (angle += 2) % 360;
        return renderer.render(scene, camera);
      })();
    };
    create();
    dragging = false;
    prevX = 0;
    prevY = 0;
    win.addEventListener('mousewheel', function(e) {
      camera.position.z += e.wheelDelta / 100;
      renderer.render(scene, camera);
      return e.preventDefault();
    }, false);
    base = 100;
    startZoom = 0;
    document.addEventListener('gesturechange', function(e) {
      var num;
      num = e.scale * base - base;
      camera.position.z = startZoom - num;
      renderer.render(scene, camera);
      return e.preventDefault();
    }, false);
    document.addEventListener('gesturestart', function() {
      return startZoom = camera.position.z;
    }, false);
    doc.addEventListener('touchstart', function(e) {
      return e.preventDefault();
    }, false);
    doc.addEventListener(MOUSE_DOWN, function(e) {
      dragging = true;
      prevX = isTouch ? e.touches[0].pageX : e.pageX;
      return prevY = isTouch ? e.touches[0].pageY : e.pageY;
    }, false);
    moveX = camera.position.x;
    moveY = camera.position.y;
    doc.addEventListener(MOUSE_MOVE, function(e) {
      var pageX, pageY;
      if (dragging === false) {
        return;
      }
      pageX = isTouch ? e.touches[0].pageX : e.pageX;
      pageY = isTouch ? e.touches[0].pageY : e.pageY;
      moveX -= prevX - pageX;
      moveY += prevY - pageY;
      camera.position.y = moveY;
      camera.position.x = moveX;
      prevX = pageX;
      prevY = pageY;
      return renderer.render(scene, camera);
    }, false);
    return doc.addEventListener(MOUSE_UP, function(e) {
      return dragging = false;
    }, false);
  };
  return doc.addEventListener('DOMContentLoaded', init, false);
})(window, window.document, window);
